✨ Attempting to apply the following manifest:
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      containers:
      - name: my-container
        image: nginx
        command: ["echo", "Hello, Kubernetes!"]
      restartPolicy: Never
