✨ Attempting to apply the following manifest:
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-usage-config
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.cpu: "1"
    requests.memory: 1Gi
