✨ Attempting to apply the following manifest:
apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-app
spec:
  containers:
  - name: nginx
    image: nginx:1.21.3
  - name: mysql
    image: mysql:8.0.28
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: mysecretpassword
  - name: redis
    image: redis:6.2.5
